PROGRAM=romboot
EXTRA_COMPONENTS= ~/laptrinh/esp-open-rtos/extras/mbedtls ~/laptrinh/esp-open-rtos/extras/rboot-ota
APP_SLOT=0
BUILD_DIR=/tmp/esp8266-build-romboot
ESPTOOL = ~/laptrinh/esptool-3.3/esptool.py
include ~/laptrinh/esp-open-rtos/common.mk

